name: Hacktoberfest PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check code formatting with black
      run: |
        black --check --diff .
    
    - name: Test basic functionality
      run: |
        # Basic syntax check
        python -m py_compile c2_server.py
        python -m py_compile c2_agent.py
        if [ -f c2_server_gui.py ]; then python -m py_compile c2_server_gui.py; fi
        if [ -f crypto_utils.py ]; then python -m py_compile crypto_utils.py; fi
    
    - name: Check for Hacktoberfest compliance
      run: |
        echo "Checking PR for Hacktoberfest compliance..."
        # Check if PR has meaningful changes (more than just whitespace/comments)
        git diff --name-only HEAD^ HEAD | head -10
        echo "PR validation complete!"